### PR TITLE
Allow beeping when skipping via headset controls

### LINKED ISSUE #24: Feature: Beep when song is changed via headset button
One feature from Vanilla Music I really like is the option to beep when I change songs via double-pressing my headset's button.

The reason for this is that, with songs often starting with a few seconds of silence or fade-in, it's difficult to tell if I've paused or skipped.

Since both applications are GPLv3, you might be able to crib parts of their implementation - see https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/MediaButtonReceiver.java.

### PR DESCRIPTION
**Pull request by faho**
This is nice because telling the difference between paused playback and a song that starts with silence can be tricky.

This was inspired by the implementation in vanilla music (also GPLv3) and the beep sound was taken from there.

Fixes #24.

(The translations noise is because of windows line endings my editor apparently removed. Shouldn't be an issue)

### CODE REVIEW

**Comment by deletescape** [comment]
I think this should be defaulted to `false` as a beep when skipping isn't usually expected behaviour. Might just be a personal preference though

**Comment by timusus** [comment]
Thanks, looks pretty good to me. 

If this is from Vanilla Music, can you add the license to assets/info.html and assets/info_dark.html (licensees are listed at the bottom).

I'm not sure if this should be off by default.. Having it on promotes feature discoverability, but if may annoy some users.

**Comment by deletescape** [comment]
I personally still tend to think it should be off by default, this is not just some visual feature, it might actually impact the listening experience. Not trying to be picky here, I see the point of feature discoverability too :blush:. I just think that this could actually be something which could make users uninstall this app because that beeping might be annoying to them.

**Comment by faho** [comment]
>If this is from Vanilla Music, can you add the license to assets/info.html and assets/info_dark.html (licensees are listed at the bottom).

Will do. Though the beep sound is really just the first thing I had ready, we could also download something from some CC-sound site. Maybe also a comment in the code?

>I personally still tend to think it should be off by default, this is not just some visual feature, it might actually impact the listening experience.

@deletescape: What this does is beep _when you've pressed the remote "next" combination_. In my case that means double-pressing the one "control" button on the little remote on my headset's cable. And because it seems to go into powersaving or something (haven't found much info on this, but since it happens with every single application I'm assuming it's the OS or hardware doing it), the first press is often swallowed so I end up pausing instead. When you go to the next song by any other means, the sound should not be played. That means e.g. it doesn't occur between songs so you could still have proper gapless playback.

This kind of remote is the most common one I've seen and from all I know all suffer from the same issues, so I'd argue for defaulting to on (and that's why I've written it that way). I'll defer to @timusus though.

----

One thing I'd love to have feedback on is the wording of the option, as everything I've come up with seems a bit verbose to me.

**Comment by timusus** [comment]
No longer required to add Vanilla's license details - we're not using the beep sound, and the tiny amount of code that we do have is different enough that I don't think we need to bother for now.

**Pull request merged**
