### PR TITLE
[WIP] Migrate to Glide 4.7

### PR DESCRIPTION
**Pull request by pschichtel**
This implements issue #167 
I've done most of the work of migrating the codebase to the new APIs, especially the use of the RequestOptions object instead of directly setting the options to on the RequestBuilder. I could have used the generated API, but I think this way a lot of configuration code could be centralized once the migration has stablized.

Currently the code base does not compile as the DataFetcher related components are still broken and didn't get to properly look at it yet.

### CODE REVIEW

**Comment by timusus** [comment]
Thanks for your hard work. I'll see if I can have a look at the DataFetcher stuff myself. 

I won't merge this one in until it's compiling.

**Comment by pschichtel** [comment]
@timusus I might take a shot at completing this today or tomorrow. Are you reachable on IRC or so in case I get stuck? We have quite a time difference, but I tend to stay up late

**Comment by timusus** [comment]
I'm happy to chat on Slack. You can join here:
http://shuttle-slack-inviter.herokuapp.com/

**Comment by pschichtel** [comment]
Sorry, but I'm currently unable to allocate time to this, sadly. Feel free to take this over if you want.

**Pull request closed without merging**
