### PR TITLE
Proposed workaround for #106

### PR DESCRIPTION
**Pull request by larsdroid**
#106

### CODE REVIEW

**Comment by timusus** [comment]
One issue I have with this fix, is I imagine it slows down the time it takes to build the media library in Shuttle (each tab, artists, albums, songs, etc.) starts with a Song object being built from the `MediaStore`. Reading id3 tags via `jAudioTagger` is relatively slow, especially compared to retrieving data from the `MediaStore`.

It's always good to measure first, so I don't want to say too much - but I'm fairly certain this change will introduce delays in perceived startup time (building of the media library), which will be even more problematic for users with large libraries.

You could test the performance difference via the `getSongsRelay()` method in `DataManager` if you like.

It might also be a good idea to add a settings option to toggle this feature, explaining to users what the potential consequences are.

Secondly, if we're going to do this for track names, shouldn't we also do it for artist and album names?

**Comment by larsdroid** [comment]
Yes, some difference in performance would make sense. I did a very quick test with only three albums, but noticed no difference (only 7ms to load the library before and after patch).
I'll do a comparison on my phone (about 30 albums). Depending on the outsome it would be best to hide this behind a checkbox.

Indeed, artists and album names should be treated in the same way.

**Comment by timusus** [comment]
I've just done a quick test on my device, with ~1800 songs.

The default library load time is about 500ms. With the change to read id3 tags, the library load time is 23-27 seconds.

This is a dramatic slow-down in library loading speed, and definitely isn't something I'd want in the app, even behind a checkbox. 

The only way forward, IMO, would be to have Shuttle run a service at boot which scans the library, reads the tags and populates a custom database, which Shuttle then references for the media library. This is something I've considered on and off over the years, but it's a lot of effort, and I don't like the idea of users having to wait for this database to populate (say, on first launch) before they can use the app.

---

Some info on how I tested the change:

Overload the `Song` constructor with a boolean `useTagInfo`
```
    public Song(Cursor cursor) {
        this(cursor, false);
    }

    public Song(Cursor cursor, boolean useTagInfo) {

        id = cursor.getLong(cursor.getColumnIndexOrThrow(MediaStore.Audio.Media._ID));

        path = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.DATA));

        if (useTagInfo) {
            name = getTagInfo().trackName;
        }
        if (TextUtils.isEmpty(name)) {
            name = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.Audio.Media.TITLE));
        }
    ...
```

In `ShuttleApplication.onCreate()`, compare building the list of songs with `useTagInfo = true` and `useTagInfo = false`
```
long time = System.currentTimeMillis();

        Observable<List<Song>> songsObservable = SqlBriteUtils.createObservableList(ShuttleApplication.getInstance(), Song::new, Song.getQuery());
        songsObservable.subscribe(songs -> Log.i(TAG, "First took: " + (System.currentTimeMillis() - time) + "ms"));

        Observable<List<Song>> songsObservable2 = SqlBriteUtils.createObservableList(ShuttleApplication.getInstance(), cursor -> new Song(cursor, true), Song.getQuery());
        songsObservable2.subscribe(songs -> Log.i(TAG, "Second took: " + (System.currentTimeMillis() - time) + "ms"));
```

I also tried reversing the order so `songsObservable2` ran first, just in case.

**Comment by larsdroid** [comment]
Ok, that kind of delay is unacceptable.
Personally, I think this issue isn't worth more of an effort than a simple workaround. The files I've used for testing are well-formed and so this is something the Android team should fix if I'm not mistaken...

**Pull request closed without merging**
