### PR TITLE
Consider a slight redesign

### PR DESCRIPTION
**Pull request by nico151999**
Feel free to edit the design suggestions. First I wanted to add an additional kind of shared element transition to the album art when the play bar is slided up. Besides from the lack of an overview over the code I've never made that kind of animation before, so I didn't even dare to try to create it. Maybe you're willing to implement it. Thanks for your great work!

### CODE REVIEW

**Comment by timusus** [comment]
Thanks for your contribution.

I've had a look at these changes and had a bit of a discussion about them. I've decided not to merge this PR in as-is, but may adopt some of these changes in the near future.

**Comment by nico151999** [comment]
This pull request was actually more meant to be a suggestion to give you a rough impression of what I imagine what the mini bar should look like. I've made some more changes locally, just in case you're interested.

**Comment by timusus** [comment]
No worries. Probably easier to discuss these things via screenshots. We can continue the discussion via an issue if that suits.

**Comment by nico151999** [comment]
I created an issue about 8 days ago. I'd appreciate if you had a look at it. The issue's called "As discussed in the Pull request". Looking forward to your feedback. BTW, I haven't worked on design changes this week, but I'm looking forward to adding some circular reveals. I hope I can manage to add them as they provide an amazing UX.

**Pull request closed without merging**
