### PR TITLE
New F-Droid branch without trackers

### PR DESCRIPTION
**Pull request by flxholle**
I have made a version without crashlytics, etc. which matches the F-Droid inclusion criterias.

### CODE REVIEW

**Comment by flxholle** [comment]
I also made tracker-free versions of master branch here:  
https://github.com/asdoi/Shuttle/tree/master_no_tracking  
And merged some of the open pull requests here and removed trackers:  
https://github.com/asdoi/Shuttle/tree/dev_no_tracking_pr_merged

**Comment by GeoZac** [comment]
This PR in this form doesn't seem to be something the dev can work with, AFAIK the PlayStore versions are made and released from this repo, removing the CrashAnalytics would mean that playstore versions will also lack this feature, which will hinder the development.

**Comment by flxholle** [comment]
Yes I know,  @GeoZac 
the dev should create an own branch for this otherwise ,as you have mentioned, further development would become difficult :wink:

**Comment by timusus** [comment]
Thanks @asdoi . I can't merge this into dev, obviously, but I'd be happy to create an `f-droid` branch, and accept a PR there.

Probably best to just go with a fork of master for now, as the dev branch is in some kind of stasis while I figure out what I'm doing with Shuttle.

I'd rather call this 'f-droid', rather than 'no tracking'. The implication is that regular Shuttle uses 'tracking' libraries, which I don't quite agree with. Crashlytics and Firebase Analytics do collect anonymous user data, and I understand that some people object to this. But the term 'trackers' is a bit of a misnomer.

**Comment by timusus** [comment]
Branch `f-droid` created

**Comment by flxholle** [comment]
Hi @timusus 
As far as I can see it, the new `f-droid` branch is equal with the master branch, isn't it?
Well, because I made a foss :wink:  version of the `dev` branch and the `master` branch.

Also I created a merge request for f-droid, which is currently linked on my repository but not merged:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6903
So when the link changes your repository you have to create separate tags for f-droid versions, named something like `fdroid-v1.2`.
Otherwise no future updates will be built because they contain libraries that are not whitelisted.

**Comment by timusus** [comment]
That's right, the `f-droid` branch is a fork of `master`. I'm not sure I follow 100% regarding the tags, but no worries - if you let me know which tags are required, I can tag them.

Just reviewing the PR now

**Pull request closed without merging**
