### PR TITLE
New f-droid master

### PR DESCRIPTION
**Pull request by flxholle**
Second try :sweat_smile: 
Refers to #503

### CODE REVIEW

**Comment by timusus** [comment]
Thanks @asdoi

**Comment by flxholle** [comment]
Thank you, too @timusus 

Also as mentioned ago could you please create a tag `fdroid-v2.0.15` from the f-droid branch.

**Comment by flxholle** [comment]
Furthermore f-droid updates the apps through checking the git repositories for tags which matches a specific name-pattern. E.g. `fdroid-v<versionname>`.
So if you publish a new release could you please also create a tag with this pattern, so the app will automatically be updated.

**Comment by timusus** [comment]
Thanks. I've added the `fdroid-v2.0.15` tag and pushed

**Pull request merged**
