### PR TITLE
Set METADATA_KEY_TRACK_NUMBER & METADATA_KEY_NUM_TRACKS

### PR DESCRIPTION
**Pull request by deletescape**
When updating the media session, they are supported in MediaMetadataCompat

### CODE REVIEW

**Comment by deletescape** [comment]
> From memory, doing this was actually causing a crash on some device(s) somewhere between 14 and 19.

My fault, thougth our minApi was 19. Will look for either the reason of this issue or for some kind of workaround.

**Comment by Vikram984511** [comment]
Sir please help me solve this issue.
Error:Execution failed for task ':app:processAmazonFreeReleaseGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\user\Shuttle\app\src\amazonFree\release\google-services.json
  C:\Users\user\Shuttle\app\src\release\amazonFree\google-services.json
  C:\Users\user\Shuttle\app\src\amazonFree\google-services.json
  C:\Users\user\Shuttle\app\src\release\google-services.json
  C:\Users\user\Shuttle\app\google-services.json

**Comment by deletescape** [comment]
Apparently below api21 NUM_TRACKS is indeed not supported at all (refer to https://android.googlesource.com/platform/frameworks/support/+/be86ab9dfd8b5c1d5ecd534cedd61949c0ec78d8) I will add a check for Lollipop before setting those values!

**Comment by deletescape** [comment]
@timusus This should fully work now on ALL API levels by looking at https://android.googlesource.com/platform/frameworks/support/+/be86ab9dfd8b5c1d5ecd534cedd61949c0ec78d8 I think though that it should actually work without this workaround, but lets better be save!

**Pull request merged**
